# coding: utf-8
require 'csv'

csv_data = CSV.read('db/seed.csv', headers: true)
csv_data.each do |data|
  Brand.create(brand: data)
end
LargeCategory.create(genre: 'レディース')
LargeCategory.create(genre: 'メンズ')
LargeCategory.create(genre: 'ベビー・キッズ')
LargeCategory.create(genre: 'インテリア・住まい・小物')
LargeCategory.create(genre: '本・音楽・ゲーム')
LargeCategory.create(genre: 'おもちゃ・ホビー・グッズ')
# # LargeCategory.create(genre: 'コスメ・香水・美容')
# # LargeCategory.create(genre: '家電・スマホ・カメラ')
# # LargeCategory.create(genre: 'スポーツ・レジャー')
# # LargeCategory.create(genre: 'ハンドメイド')
# # LargeCategory.create(genre: 'チケット')
# # LargeCategory.create(genre: '自動車・オートバイ')
# # LargeCategory.create(genre: 'その他')

MiddleCategory.create(genre: 'トップス',large_category_id: '1')
MiddleCategory.create(genre: 'ジャケット/アウター',large_category_id: '1')
MiddleCategory.create(genre: 'パンツ',large_category_id: '1')
MiddleCategory.create(genre: 'スカート',large_category_id: '1')
MiddleCategory.create(genre: 'ワンピース',large_category_id: '1')
MiddleCategory.create(genre: 'トップス',large_category_id: '2')
MiddleCategory.create(genre: 'ジャケット/アウター',large_category_id: '2')
MiddleCategory.create(genre: 'パンツ',large_category_id: '2')
MiddleCategory.create(genre: '靴',large_category_id: '2')
MiddleCategory.create(genre: 'バッグ',large_category_id: '2')
MiddleCategory.create(genre: 'ベビー服(女の子用)  ~95cm',large_category_id: '3')
MiddleCategory.create(genre: 'ベビー服(男の子用)  ~95cm',large_category_id: '3')
MiddleCategory.create(genre: 'ベビー服(男女兼用)  ~95cm',large_category_id: '3')
MiddleCategory.create(genre: 'キッズ服(女の子用) 100cm~',large_category_id: '3')
MiddleCategory.create(genre: 'キッズ服(男の子用) 100cm~',large_category_id: '3')
MiddleCategory.create(genre: 'キッチン/食器',large_category_id: '4')
MiddleCategory.create(genre: 'ベッド/マットレス',large_category_id: '4')
MiddleCategory.create(genre: 'ソファ/ソファベッド',large_category_id: '4')
MiddleCategory.create(genre: '椅子/チェア',large_category_id: '4')
MiddleCategory.create(genre: '机/テーブル',large_category_id: '4')
MiddleCategory.create(genre: '本',large_category_id: '5')
MiddleCategory.create(genre: '漫画',large_category_id: '5')
MiddleCategory.create(genre: '雑誌',large_category_id: '5')
MiddleCategory.create(genre: 'CD',large_category_id: '5')
MiddleCategory.create(genre: 'DVD/ブルーレイ',large_category_id: '5')
MiddleCategory.create(genre: 'おもちゃ',large_category_id: '6')
MiddleCategory.create(genre: 'タレントグッズ',large_category_id: '6')
MiddleCategory.create(genre: 'コミック/アニメグッズ',large_category_id: '6')
MiddleCategory.create(genre: 'トレーディングカード',large_category_id: '6')
MiddleCategory.create(genre: 'フィギュア',large_category_id: '6')


SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '1')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '1')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '2')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '2')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '3')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '3')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '4')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '4')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '5')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '5')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '6')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '6')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '7')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '7')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '8')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '8')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '9')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '9')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '10')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '10')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '11')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '11')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '12')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '12')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '13')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '13')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '14')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '14')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '15')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '15')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '16')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '16')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '17')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '17')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '18')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '18')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '19')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '19')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '20')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '20')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '21')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '21')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '22')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '22')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '23')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '23')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '24')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '24')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '25')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '25')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '26')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '26')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '27')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '27')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '28')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '28')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '29')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '29')
SmallCategory.create(genre: '仮カテゴリー1',middle_category_id: '30')
SmallCategory.create(genre: '仮カテゴリー2',middle_category_id: '30')



